GET http://localhost:8080/api/v1/flowers
### Test POST Add Flower
POST http://localhost:8080/api/v1/flowers
Content-Type: application/json

{
  "name": "Romashka",
  "color": "Yellow",
  "price": 15.8,
  "available": true
}